namespace Tharga.Fortnox;

/// <summary>
/// Fortnox Assignment object
/// </summary>
public record FortnoxAssignment
{
    /// <summary>
    /// Request code from Fortnox used to connect the application with Fortnox.
    /// </summary>
    public string Code { get; init; }

    /// <summary>
    /// Code generated by your application that was provided with 'BuildConnectUriAsync'.
    /// </summary>
    public Guid RequestKey { get; init; }
}